default:
    Smtp_Server: smtp.mxhichina.com
    Smtp_Sender: test@tenez.com
    Password: Password
    OnLine_Receiver: techtest@tenez.com
    on-off: on


custom:
    Smtp_Server: xxx
    Smtp_Sender: test@tenez.com
    Password: Password
    OnLine_Receiver: techtest@tenez.com
    on-off: on

worker:
    -   a: 1
        b: 3
    -   c: 4
        d: 5
