default:
    Smtp_Server: smtp.mxhichina.com
    Smtp_Sender: test@tenez.com
    Password: Password
    OnLine_Receiver: techtest@tenez.com
    on-off: on
    type: !!python/object:__main__.AlgoType {Online}


custom:
    Smtp_Server: xxx
    Smtp_Sender: test@tenez.com
    Password: Password
    OnLine_Receiver: techtest@tenez.com
    on-off: on
#    type: !!python/object:__main__.AlgoType {Offline}
